defmodule EncounterforgeWeb.ForgeLive do
  use EncounterforgeWeb, :live_view

  alias Encounterforge.Encounter

  @max_vibe_length 200
  @cooldown_ms 3_000

  def mount(_params, _session, socket) do
    {:ok, assign(socket, encounter: Encounter.generate_mock(), loading: false, vibe: "", last_submit_at: nil)}
  end

  def render(assigns) do
    ~H"""
    <div class="min-h-screen bg-stone-100 py-12 px-4 sm:px-6 lg:px-8 font-serif">
      <div class="max-w-3xl mx-auto">

        <header class="text-center mb-12">
          <h1 class="text-5xl font-extrabold text-stone-900 tracking-tight">
            Encounter<span class="text-red-800">Forge</span>
          </h1>
          <p class="mt-3 text-lg text-stone-600 italic">"The Forge weaves the tale - you provide the spark."</p>
        </header>

        <section class="bg-white p-8 rounded-lg shadow-md border border-stone-200">
          <form phx-submit="save_vibe" class="space-y-4">
            <div>
              <label for="vibe" class="block text-sm font-bold text-stone-700 uppercase tracking-widest">The Vibe</label>
              <div class="mt-1 flex gap-2">
                <input
                  type="text"
                  name="user_input"
                  id="vibe"
                  value={@vibe}
                  required
                  maxlength="200"
                  placeholder="e.g. A cursed lighthouse at the edge of the world..."
                  class="block w-full rounded-md border-stone-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm p-3 border"
                />
                <button
                  type="submit"
                  disabled={@loading}
                  class="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-red-800 hover:bg-red-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 disabled:bg-stone-400 transition-colors"
                >
                  <%= if @loading do %>
                    <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                      <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Forging...
                  <% else %>
                    Forge
                  <% end %>
                </button>
              </div>
            </div>
          </form>
        </section>

        <%= if @encounter do %>
          <article class="mt-12 bg-white shadow-2xl rounded-sm border-t-8 border-red-800 overflow-hidden transform transition-all animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div class="p-8 sm:p-12 space-y-8">

              <header class="border-b border-stone-200 pb-6">
                <h2 class="text-3xl font-black text-stone-900 mb-2 leading-tight">
                  {@encounter.title}
                </h2>
                <div class="flex items-center text-stone-500 text-sm uppercase tracking-tighter mt-4">
                  <span class="mr-2">Scene Generated by the Forge</span>
                  <div class="h-px flex-1 bg-stone-200"></div>
                </div>
                <p class="text-stone-600 text-sm leading-relaxed font-sans mt-2">{@encounter.location}</p>
              </header>

              <div class="grid grid-cols-1 md:grid-cols-2 gap-12">
                <section>
                  <h3 class="text-xs font-bold text-red-800 uppercase tracking-widest mb-2">Opposition</h3>
                  <p class="text-stone-700 leading-relaxed font-sans"><%= @encounter.monsters %></p>
                  <p class="mt-4 text-stone-600 text-sm border-l-2 border-stone-200 pl-4 font-sans italic">
                    <span class="font-bold text-stone-500 uppercase text-xs block mb-1">Motivation</span>
                    <%= @encounter.motivation %>
                  </p>
                </section>
                <section>
                  <h3 class="text-xs font-bold text-green-800 uppercase tracking-widest mb-2">Loot</h3>
                  <p class="text-stone-700 text-sm font-sans"><%= @encounter.loot %></p>
                </section>
              </div>

              <div class="bg-stone-50 -mx-8 sm:-mx-12 p-8 sm:p-12 mt-8 grid grid-cols-1 md:grid-cols-2 gap-12 border-t border-stone-100">
                <section>
                  <h3 class="text-xs font-bold text-amber-600 uppercase tracking-widest mb-2">Complication</h3>
                  <p class="text-stone-700 text-sm font-sans"><%= @encounter.complication %></p>
                </section>
                <section>
                  <h3 class="text-xs font-bold text-blue-800 uppercase tracking-widest mb-2">Twist</h3>
                  <p class="text-stone-800 text-sm font-sans"><%= @encounter.twist %></p>
                </section>
              </div>

            </div>
          </article>
        <% end %>

        <%= if !@encounter && !@loading do %>
          <div class="mt-20 text-center space-y-4 opacity-40">
            <div class="flex justify-center space-x-4">
              <div class="w-12 h-1 bg-stone-300"></div>
              <div class="w-1 h-1 bg-stone-300 rounded-full"></div>
              <div class="w-12 h-1 bg-stone-300"></div>
            </div>
            <p class="text-stone-500 italic">Describe the scene to begin...</p>
          </div>
        <% end %>
      </div>
    </div>
    """
  end

  def handle_event("save_vibe", %{"user_input" => input}, socket) do
    now = System.monotonic_time(:millisecond)
    input = String.slice(input, 0, @max_vibe_length)

    cond do
      throttled?(socket.assigns.last_submit_at, now) ->
        {:noreply, socket}

      String.trim(input) == "" ->
        {:noreply, socket}

      true ->
        socket = assign(socket, loading: true, encounter: nil, vibe: input, last_submit_at: now)

        Task.async(fn ->
          Encounterforge.AI.fetch_encounter(input)
        end)

        {:noreply, socket}
    end
  end

  defp throttled?(nil, _now), do: false
  defp throttled?(last, now), do: now - last < @cooldown_ms

  # SUCCESS: Handle the AI response
  def handle_info({_ref, {:ok, encounter}}, socket) do
    {:noreply, assign(socket, loading: false, encounter: encounter)}
  end

  # ERROR: Handle failures
  def handle_info({_ref, {:error, _reason}}, socket) do
    {:noreply, assign(socket, loading: false)}
  end

  # CATCH-ALL: Handle the :DOWN message from Task.async
  def handle_info({:DOWN, _ref, :process, _pid, _reason}, socket) do
    {:noreply, socket}
  end

  # ULTIMATE CATCH-ALL: Keeps the process from crashing on unknown messages
  def handle_info(_msg, socket) do
    {:noreply, socket}
  end
end
